### PR TITLE
Added grid breakpoint and grid container overrides

### PR DESCRIPTION
**Pull request by silviatc**
I could check lines 33, 34, and 43 and see if they need to be included

### CODE REVIEW

**Comment by GeorgeTaveras1231** [comment]
@silviatc Those lines seem to be quick tests to make sure the grid 'makes sense'

**Comment by silviatc** [comment]
@GeorgeTaveras1231 sounds good! do I merge or do you merge?

**Comment by GeorgeTaveras1231** [comment]
@silviatc I'm doing a quick check to make sure the grid actually changes :)

**Comment by GeorgeTaveras1231** [comment]
@silviatc there was a small bug that didn't allow the new grid values to be set. It seems (based on my observation) that once variables are set with the `!default` macro (as they are by tw bootstrap), Then using the `!default` macro again leaves the variable untouched. To fix the problem, I removed the `!default` macro and that fixed the grid.

**Comment by GeorgeTaveras1231** [comment]
All good 👍

**Pull request merged**
